# Generated by Django 5.0.7 on 2024-08-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='email',
            field=models.EmailField(default=None, max_length=255),
        ),
    ]
