# Generated by Django 4.2.6 on 2024-08-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_shipping_order_with_respect_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
