# Generated by Django 4.1.13 on 2024-06-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_persone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persone',
        ),
    ]
