# Generated by Django 4.1.13 on 2024-06-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
