# Generated by Django 4.1.13 on 2024-07-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_remove_user_produits_delete_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
