# Generated by Django 4.1.13 on 2024-07-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_produit_matricule'),
        ('authen', '0010_alter_profile_produits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Produits',
        ),
        migrations.AddField(
            model_name='profile',
            name='Produits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.produit'),
        ),
    ]
