# Generated by Django 4.1.13 on 2024-07-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_produit_matricule'),
        ('authen', '0011_remove_profile_produits_profile_produits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Produits',
        ),
        migrations.AddField(
            model_name='profile',
            name='Produits',
            field=models.ManyToManyField(to='myapp.produit'),
        ),
    ]
