# Generated by Django 4.1.13 on 2024-07-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_produit_matricule'),
        ('authen', '0012_remove_profile_produits_profile_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Produits',
            field=models.ManyToManyField(blank=True, to='myapp.produit'),
        ),
    ]
