# Generated by Django 4.2.6 on 2024-08-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_produit_category'),
        ('authen', '0016_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='myapp.produit'),
        ),
    ]
