# Generated by Django 4.2.6 on 2024-08-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0017_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
