# Generated by Django 5.0.6 on 2024-06-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='matricule',
            field=models.CharField(default='262x', max_length=200),
        ),
    ]
