# Generated by Django 4.1.13 on 2024-07-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_produit_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='matricule',
        ),
    ]
