# Generated by Django 5.0.7 on 2024-08-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_produit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
    ]
