# Generated by Django 5.0.7 on 2024-08-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_produit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='category',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
