# Generated by Django 5.0.7 on 2024-08-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_produit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('table', 'table'), ('chair', 'chair'), ('sofa', 'sofa'), ('shelving', 'shelving')], default=None, max_length=20),
        ),
    ]
