# Generated by Django 5.0.7 on 2024-08-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_produit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('chair', 'chair'), ('sofa', 'sofa'), ('shelving', 'shelving'), ('table', 'table')], default=None, max_length=20),
        ),
    ]
