# Generated by Django 5.0.7 on 2024-08-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_produit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('table', 'table'), ('shelving', 'shelving'), ('sofa', 'sofa'), ('chair', 'chair')], default=None, max_length=20),
        ),
    ]
