# Generated by Django 5.0.7 on 2024-08-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_produit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('chair', 'chair'), ('shelving', 'shelving'), ('table', 'table'), ('sofa', 'sofa')], default=None, max_length=20),
        ),
    ]
