# Generated by Django 4.2.6 on 2024-08-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_produit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('sofa', 'sofa'), ('chair', 'chair'), ('shelving', 'shelving'), ('table', 'table')], default=None, max_length=20),
        ),
    ]
