# Generated by Django 4.2.6 on 2024-08-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_produit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('shelving', 'shelving'), ('sofa', 'sofa'), ('chair', 'chair'), ('table', 'table')], default=None, max_length=20),
        ),
    ]
