# Generated by Django 4.2.6 on 2024-08-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_produit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('table', 'table'), ('shelving', 'shelving'), ('sofa', 'sofa'), ('chair', 'chair')], default=None, max_length=20),
        ),
    ]
