# Generated by Django 4.2.6 on 2024-08-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_produit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('shelving', 'shelving'), ('sofa', 'sofa'), ('table', 'table'), ('chair', 'chair')], default=None, max_length=20),
        ),
    ]
