# Generated by Django 4.2.6 on 2024-09-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_produit_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('Kid', 'Kid'), ('Women', 'Women'), ('Man', 'Man')], default=None, max_length=20),
        ),
    ]
