# Generated by Django 4.2.6 on 2024-10-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_produit_description_alter_produit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('Women', 'Women'), ('Kid', 'Kid'), ('Man', 'Man')], default=None, max_length=20),
        ),
    ]
